
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hunia
 */
public class ElectionMainScreen extends javax.swing.JFrame {
    private String uid;
    /**
     * Creates new form ElectionScreen1
     */
    public ElectionMainScreen(String uid) {
        this.uid = uid;
        initComponents();
        displayData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        ProfileLb = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        logoLb = new javax.swing.JLabel();
        HomeLb = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        AboutusLb = new javax.swing.JLabel();
        FeedbackLb = new javax.swing.JLabel();
        footerPanel = new javax.swing.JPanel();
        headerLb = new javax.swing.JLabel();
        LogoLb = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        selectionPanel = new javax.swing.JPanel();
        selectionLb = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        registerBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(231, 231, 231));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProfileLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ProfileLb.setForeground(new java.awt.Color(255, 255, 255));
        ProfileLb.setText("Profile");
        ProfileLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProfileLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ProfileLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileLbMouseClicked(evt);
            }
        });
        mainPanel.add(ProfileLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 60, -1));

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Go Back");
        backBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), java.awt.Color.black));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        mainPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 70, 30));

        headerPanel.setBackground(new java.awt.Color(0, 0, 0));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_full_w.png"))); // NOI18N
        headerPanel.add(logoLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 130, 80));

        HomeLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HomeLb.setForeground(new java.awt.Color(255, 255, 255));
        HomeLb.setText("Home");
        HomeLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        HomeLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeLbMouseClicked(evt);
            }
        });
        headerPanel.add(HomeLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 60, -1));

        logoutBtn.setBackground(new java.awt.Color(244, 189, 108));
        logoutBtn.setText("Log out");
        logoutBtn.setBorder(null);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        headerPanel.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 80, 30));

        AboutusLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AboutusLb.setForeground(new java.awt.Color(255, 255, 255));
        AboutusLb.setText("About us");
        AboutusLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AboutusLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AboutusLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutusLbMouseClicked(evt);
            }
        });
        headerPanel.add(AboutusLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 60, -1));

        FeedbackLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FeedbackLb.setForeground(new java.awt.Color(255, 255, 255));
        FeedbackLb.setText("Feedback");
        FeedbackLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FeedbackLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        FeedbackLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FeedbackLbMouseClicked(evt);
            }
        });
        headerPanel.add(FeedbackLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 60, -1));

        mainPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 90));

        footerPanel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        mainPanel.add(footerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, -1, -1));

        headerLb.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        headerLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLb.setText("Moderated Elections");
        mainPanel.add(headerLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 380, 50));

        LogoLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/12.png"))); // NOI18N
        mainPanel.add(LogoLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, 70));

        deleteBtn.setBackground(new java.awt.Color(244, 189, 108));
        deleteBtn.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.setBorder(null);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        mainPanel.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 100, 30));

        createBtn.setBackground(new java.awt.Color(244, 189, 108));
        createBtn.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        createBtn.setText("Create");
        createBtn.setBorder(null);
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        mainPanel.add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 100, 30));

        viewBtn.setBackground(new java.awt.Color(244, 189, 108));
        viewBtn.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        viewBtn.setText("View");
        viewBtn.setBorder(null);
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        mainPanel.add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 100, 30));

        jScrollPane.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane.setToolTipText("");

        jTable.setBackground(new java.awt.Color(244, 189, 108));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Category", "Start Date", "Result Date", "Country", "Privacy"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane.setViewportView(jTable);

        mainPanel.add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 810, 170));

        selectionPanel.setBackground(new java.awt.Color(0, 0, 0));
        selectionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectionLb.setBackground(new java.awt.Color(0, 0, 0));
        selectionLb.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        selectionLb.setForeground(new java.awt.Color(255, 255, 255));
        selectionLb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        selectionLb.setText("Select Election:");
        selectionPanel.add(selectionLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 30));

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectionPanel.add(jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 180, 30));

        mainPanel.add(selectionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 330, 50));

        registerBtn.setBackground(new java.awt.Color(0, 0, 0));
        registerBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerBtn.setText("Register");
        registerBtn.setBorder(null);
        registerBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        mainPanel.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 80, 30));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void displayData(){
        try{
            Checker check = new Checker();
            Statement stmt = check.connectSQL();
            //joins election and e_category to get category_type w.r.t to the election_cid
            ResultSet result = stmt.executeQuery("Select * from election join e_category on election.election_cid=e_category.category_id and moderator_uid='"+this.uid+"'");
            DefaultTableModel model = (DefaultTableModel) jTable.getModel();
           
            ArrayList<String> eid = new ArrayList<>();
            while(result.next()){
                String startdate = result.getString("startdate").substring(0,10);
                String resultdate = result.getString("resultdate").substring(0,10); 
                //storing election_ids in arrayList
                eid.add(result.getString("election_id"));
                model.addRow(new String[]{result.getString("election_id"), result.getString("election_name"), result.getString("category_type") ,startdate, resultdate, result.getString("country"), result.getString("privacy")});
            }
            
            //adding election_ids from arrayList into ComboBox
            DefaultComboBoxModel dml= new DefaultComboBoxModel();
            for (int i = 0; i < eid.size(); i++) {
              dml.addElement(eid.get(i));
            }
            jComboBox.setModel(dml);   
        }
        catch(Exception ex){
                System.out.println(ex.toString());
        }
    }
    
    
    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        try{
            int confirmation = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete the election?", "Deletion Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if(confirmation == JOptionPane.YES_OPTION){
                Checker check = new Checker();
                Statement stmt = check.connectSQL();

                String eid = jComboBox.getSelectedItem().toString();

                ResultSet result = stmt.executeQuery("Select election_cid, category_type from election join e_category on election.election_cid=e_category.category_id and election_id='"+eid+"'");
                result.next();
                String cid = result.getString(1);
                String ctype = result.getString(2);
             
                if(ctype.equalsIgnoreCase("Government")){
                    stmt.executeQuery("DELETE FROM government WHERE election_cid='"+cid+"'");
                }
                else if(ctype.equalsIgnoreCase("Custom")){
                    stmt.executeQuery("DELETE FROM custom WHERE election_cid='"+cid+"'");
                }
                else if(ctype.equalsIgnoreCase("Organization")){
                    stmt.executeQuery("DELETE FROM organizations WHERE election_cid='"+cid+"'");
                }
                else if(ctype.equalsIgnoreCase("Referendum")){
                    stmt.executeQuery("DELETE FROM referendum WHERE election_cid='"+cid+"'");
                }
                
                stmt.executeQuery("DELETE FROM vote WHERE election_id='"+eid+"'");
                stmt.executeQuery("DELETE FROM candidateapplicants WHERE election_id='"+eid+"'");
                stmt.executeQuery("DELETE FROM groupapplicants WHERE election_id='"+eid+"'");
                stmt.executeQuery("DELETE FROM registrations WHERE election_id='"+eid+"'");  
                stmt.executeQuery("DELETE FROM e_category WHERE category_id='"+cid+"'");
                stmt.executeQuery("DELETE FROM election WHERE election_id='"+eid+"'");
                
                DefaultTableModel model = (DefaultTableModel) jTable.getModel();
                model.setRowCount(0);
                this.uid = "u-123";
                //joins election and e_category to get category_type w.r.t to the election_cid
                result = stmt.executeQuery("Select * from election join e_category on election.election_cid=e_category.category_id and moderator_uid='"+this.uid+"'");

                ArrayList<String> eids = new ArrayList<>();
                while(result.next()){
                    String startdate = result.getString("startdate").substring(0,10);
                    String resultdate = result.getString("resultdate").substring(0,10); 
                    //storing election_ids in arrayList
                    eids.add(result.getString("election_id"));
                    model.addRow(new String[]{result.getString("election_id"), result.getString("election_name"), result.getString("category_type") ,startdate, resultdate, result.getString("country"), result.getString("privacy")});
                }

                //adding election_ids from arrayList into ComboBox
                DefaultComboBoxModel dml= new DefaultComboBoxModel();
                for (int i = 0; i < eids.size(); i++) {
                  dml.addElement(eids.get(i));
                }
                jComboBox.setModel(dml);  
            }         
             
        }
        catch(Exception ex){
                System.out.println(ex.toString());
                ex.printStackTrace();
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        dispose();
        ElectionCreateEdit1 electionCreate = new ElectionCreateEdit1(uid, new ArrayList<>());
        electionCreate.setVisible(true);                //frame will only be visible with set "true"
        electionCreate.setLocationRelativeTo(null);     //for opening in center
    }//GEN-LAST:event_createBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        dispose();
        ElectionView1 electionView = new ElectionView1(uid, jComboBox.getSelectedItem().toString());
        electionView.setVisible(true);                //frame will only be visible with set "true"
        electionView.setLocationRelativeTo(null);     //for opening in center
    }//GEN-LAST:event_viewBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        dispose();
        MainScreen main = new MainScreen(uid);
        main.setVisible(true);                //frame will only be visible with set "true"
        main.setLocationRelativeTo(null);     //for opening in center
    }//GEN-LAST:event_backBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        registrationVote vote = new registrationVote(uid);
        vote.setVisible(true);                //frame will only be visible with set "true"
        vote.setLocationRelativeTo(null); 
        
    }//GEN-LAST:event_registerBtnActionPerformed

    private void HomeLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeLbMouseClicked
        dispose();
        MainScreen main = new MainScreen(uid);
        main.setVisible(true);                //frame will only be visible with set "true"
        main.setLocationRelativeTo(null);     //for opening in center
    }//GEN-LAST:event_HomeLbMouseClicked

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        int result = JOptionPane.showConfirmDialog(null,"Are you sure you want to log out?", "Logout Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(result == JOptionPane.YES_OPTION){
            dispose();
            Homepage home = new Homepage();
            home.setVisible(true);                //frame will only be visible with set "true"
            home.setLocationRelativeTo(null);     //for opening in center
        }   
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void AboutusLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutusLbMouseClicked
        // TODO add your handling code here:
        dispose();
        AboutUs about= new AboutUs();
        about.setVisible(true);
        about.setLocationRelativeTo (null);
    }//GEN-LAST:event_AboutusLbMouseClicked

    private void FeedbackLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FeedbackLbMouseClicked
        // TODO add your handling code here:
       
        Feedback feed = new Feedback(uid);
        feed.setVisible(true);                //frame will only be visible with set "true"
        feed.setLocationRelativeTo(null);     //for opening in center
    }//GEN-LAST:event_FeedbackLbMouseClicked

    private void ProfileLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileLbMouseClicked
        Profile1 profile = new Profile1(uid);
        profile.setVisible(true);                //frame will only be visible with set "true"
        profile.setLocationRelativeTo(null);     //for opening in center
    }//GEN-LAST:event_ProfileLbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElectionMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElectionMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElectionMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElectionMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElectionMainScreen(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutusLb;
    private javax.swing.JLabel FeedbackLb;
    private javax.swing.JLabel HomeLb;
    private javax.swing.JLabel LogoLb;
    private javax.swing.JLabel ProfileLb;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JLabel headerLb;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel logoLb;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel selectionLb;
    private javax.swing.JPanel selectionPanel;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
