
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hunia
 */
public class ElectionView1 extends javax.swing.JFrame {
    private String uid;
    private String eid;
    /**
     * Creates new form ElectionView1
     */
    public ElectionView1(String uid, String eid) {
        this.uid = uid;
        this.eid = eid;
        initComponents();
        displayData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerLb = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        logoLb = new javax.swing.JLabel();
        HomeLb = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        AboutusLb = new javax.swing.JLabel();
        FeedbackLb = new javax.swing.JLabel();
        ProfileLb = new javax.swing.JLabel();
        footerPanel = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        nameLb = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        startdateLb = new javax.swing.JLabel();
        startdateField = new javax.swing.JFormattedTextField();
        enddateLb = new javax.swing.JLabel();
        enddateField = new javax.swing.JFormattedTextField();
        resultdateLb = new javax.swing.JLabel();
        resultdateField = new javax.swing.JFormattedTextField();
        privacyLb = new javax.swing.JLabel();
        privacyField = new javax.swing.JComboBox<>();
        cityLb = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        countryLb = new javax.swing.JLabel();
        countryField = new javax.swing.JComboBox<>();
        descLb = new javax.swing.JLabel();
        descField = new javax.swing.JScrollPane();
        descArea = new javax.swing.JTextArea();
        backBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(231, 231, 231));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        headerLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLb.setText("Election Details");
        mainPanel.add(headerLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 680, 50));

        headerPanel.setBackground(new java.awt.Color(0, 0, 0));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_full_w.png"))); // NOI18N
        headerPanel.add(logoLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 130, 80));

        HomeLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HomeLb.setForeground(new java.awt.Color(255, 255, 255));
        HomeLb.setText("Home");
        HomeLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        HomeLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeLbMouseClicked(evt);
            }
        });
        headerPanel.add(HomeLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 60, -1));

        logoutBtn.setBackground(new java.awt.Color(244, 189, 108));
        logoutBtn.setText("Log out");
        logoutBtn.setBorder(null);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        headerPanel.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 80, 30));

        AboutusLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AboutusLb.setForeground(new java.awt.Color(255, 255, 255));
        AboutusLb.setText("About us");
        AboutusLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AboutusLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AboutusLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutusLbMouseClicked(evt);
            }
        });
        headerPanel.add(AboutusLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 60, -1));

        FeedbackLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FeedbackLb.setForeground(new java.awt.Color(255, 255, 255));
        FeedbackLb.setText("Feedback");
        FeedbackLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FeedbackLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        FeedbackLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FeedbackLbMouseClicked(evt);
            }
        });
        headerPanel.add(FeedbackLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 60, -1));

        ProfileLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ProfileLb.setForeground(new java.awt.Color(255, 255, 255));
        ProfileLb.setText("Profile");
        ProfileLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProfileLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ProfileLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileLbMouseClicked(evt);
            }
        });
        headerPanel.add(ProfileLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 60, -1));

        mainPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 90));

        footerPanel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        mainPanel.add(footerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, 10));

        infoPanel.setBackground(new java.awt.Color(244, 189, 108));
        infoPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray));
        infoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLb.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        nameLb.setText("Name");
        infoPanel.add(nameLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 90, 30));

        nameField.setEditable(false);
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        infoPanel.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 230, 30));

        startdateLb.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        startdateLb.setText("Start Date");
        infoPanel.add(startdateLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 30));

        startdateField.setEditable(false);
        startdateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startdateFieldActionPerformed(evt);
            }
        });
        infoPanel.add(startdateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 100, 30));

        enddateLb.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        enddateLb.setText("End Date");
        infoPanel.add(enddateLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 80, 30));

        enddateField.setEditable(false);
        enddateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enddateFieldActionPerformed(evt);
            }
        });
        infoPanel.add(enddateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 100, 30));

        resultdateLb.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        resultdateLb.setText("Result Date");
        infoPanel.add(resultdateLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 90, 30));

        resultdateField.setEditable(false);
        resultdateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultdateFieldActionPerformed(evt);
            }
        });
        infoPanel.add(resultdateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 100, 30));

        privacyLb.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        privacyLb.setText("Privacy");
        infoPanel.add(privacyLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 70, 30));

        privacyField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Private", "Public" }));
        privacyField.setEnabled(false);
        infoPanel.add(privacyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 170, 30));

        cityLb.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        cityLb.setText("City");
        infoPanel.add(cityLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 90, 30));

        cityField.setEditable(false);
        cityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityFieldActionPerformed(evt);
            }
        });
        infoPanel.add(cityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 230, 30));

        countryLb.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        countryLb.setText("Country");
        infoPanel.add(countryLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 80, 30));

        countryField.setEnabled(false);
        countryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryFieldActionPerformed(evt);
            }
        });
        infoPanel.add(countryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 170, 30));

        descLb.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        descLb.setText("Description");
        infoPanel.add(descLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 90, 20));

        descArea.setEditable(false);
        descArea.setColumns(20);
        descArea.setRows(5);
        descField.setViewportView(descArea);

        infoPanel.add(descField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 530, 70));

        mainPanel.add(infoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 680, 270));

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Go Back");
        backBtn.setBorder(null);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        mainPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 70, 30));

        nextBtn.setBackground(new java.awt.Color(0, 0, 0));
        nextBtn.setForeground(new java.awt.Color(255, 255, 255));
        nextBtn.setText("Next");
        nextBtn.setBorder(null);
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        mainPanel.add(nextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 450, 70, 30));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayData(){
        try{
            Checker check = new Checker();
            Statement stmt = check.connectSQL();
            ResultSet result = stmt.executeQuery("Select * from election where election_id='"+this.eid+"'");
            result.next();
            String startdate = result.getString("startdate").substring(0,10);
            String enddate = result.getString("enddate").substring(0,10);
            String resultdate = result.getString("resultdate").substring(0,10);
            
            startdateField.setText(startdate);
            enddateField.setText(enddate);
            resultdateField.setText(resultdate);
            nameField.setText(result.getString("election_name"));
            cityField.setText(result.getString("city"));
            descArea.setText(result.getString("election_description"));
            privacyField.setSelectedItem(result.getString("privacy"));
            privacyField.setSelectedItem(result.getString("country"));           
            }catch(Exception ex){
            System.out.println(ex.toString());
        }
    }
    
    
    
    private void HomeLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeLbMouseClicked
        dispose();
        MainScreen main = new MainScreen(uid);
        main.setVisible(true);                //frame will only be visible with set "true"
        main.setLocationRelativeTo(null);     //for opening in center
    }//GEN-LAST:event_HomeLbMouseClicked

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        int result = JOptionPane.showConfirmDialog(null,"Are you sure you want to log out?", "Logout Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(result == JOptionPane.YES_OPTION){
            dispose();
            Homepage home = new Homepage();
            home.setVisible(true);                //frame will only be visible with set "true"
            home.setLocationRelativeTo(null);     //for opening in center
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void AboutusLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutusLbMouseClicked
        // TODO add your handling code here:
        AboutUs about= new AboutUs();
        about.setVisible(true);
        about.setLocationRelativeTo (null);
    }//GEN-LAST:event_AboutusLbMouseClicked

    private void FeedbackLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FeedbackLbMouseClicked
        // TODO add your handling code here:
       
        Feedback feed = new Feedback(uid);
        feed.setVisible(true);                //frame will only be visible with set "true"
        feed.setLocationRelativeTo(null);     //for opening in center
    }//GEN-LAST:event_FeedbackLbMouseClicked

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void startdateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startdateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startdateFieldActionPerformed

    private void enddateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enddateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enddateFieldActionPerformed

    private void resultdateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultdateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultdateFieldActionPerformed

    private void cityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityFieldActionPerformed

    private void countryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryFieldActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
       
        dispose();
        ElectionMainScreen election = new ElectionMainScreen(uid);
        election.setVisible(true);                //frame will only be visible with set "true"
        election.setLocationRelativeTo(null);     //for opening in center
        

    }//GEN-LAST:event_backBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        dispose();
        ElectionView2 electionView = new ElectionView2(uid, eid);
        electionView.setVisible(true);                //frame will only be visible with set "true"
        electionView.setLocationRelativeTo(null);     //for opening in center
            

    }//GEN-LAST:event_nextBtnActionPerformed

    private void ProfileLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileLbMouseClicked
        Profile1 profile = new Profile1(uid);
        profile.setVisible(true);                //frame will only be visible with set "true"
        profile.setLocationRelativeTo(null);     //for opening in center
    }//GEN-LAST:event_ProfileLbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElectionView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElectionView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElectionView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElectionView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElectionView1("", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutusLb;
    private javax.swing.JLabel FeedbackLb;
    private javax.swing.JLabel HomeLb;
    private javax.swing.JLabel ProfileLb;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField cityField;
    private javax.swing.JLabel cityLb;
    private javax.swing.JComboBox<String> countryField;
    private javax.swing.JLabel countryLb;
    private javax.swing.JTextArea descArea;
    private javax.swing.JScrollPane descField;
    private javax.swing.JLabel descLb;
    private javax.swing.JFormattedTextField enddateField;
    private javax.swing.JLabel enddateLb;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JLabel headerLb;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel logoLb;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLb;
    private javax.swing.JButton nextBtn;
    private javax.swing.JComboBox<String> privacyField;
    private javax.swing.JLabel privacyLb;
    private javax.swing.JFormattedTextField resultdateField;
    private javax.swing.JLabel resultdateLb;
    private javax.swing.JFormattedTextField startdateField;
    private javax.swing.JLabel startdateLb;
    // End of variables declaration//GEN-END:variables
}
