
import java.awt.Component;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hunia
 */
public class ForgotPassword1 extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        uIDLb = new javax.swing.JLabel();
        uIDField = new javax.swing.JTextField();
        emailLb = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        cnicLb = new javax.swing.JLabel();
        cnicField = new javax.swing.JTextField();
        headerLb = new javax.swing.JLabel();
        logoLb = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(244, 189, 108));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoPanel.setBackground(new java.awt.Color(0, 0, 0));
        infoPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        infoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uIDLb.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        uIDLb.setForeground(new java.awt.Color(244, 189, 108));
        uIDLb.setText("User ID");
        infoPanel.add(uIDLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 100, 20));

        uIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uIDFieldActionPerformed(evt);
            }
        });
        infoPanel.add(uIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 360, 20));

        emailLb.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        emailLb.setForeground(new java.awt.Color(244, 189, 108));
        emailLb.setText("Email");
        infoPanel.add(emailLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 90, 20));

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        infoPanel.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 360, 20));

        cnicLb.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cnicLb.setForeground(new java.awt.Color(244, 189, 108));
        cnicLb.setText("CNIC");
        infoPanel.add(cnicLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 90, 20));

        cnicField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnicFieldActionPerformed(evt);
            }
        });
        infoPanel.add(cnicField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 360, 20));

        mainPanel.add(infoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 610, 180));

        headerLb.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        headerLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLb.setText("Forgot Password");
        mainPanel.add(headerLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 610, 50));

        logoLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo_cropped_black.png"))); // NOI18N
        mainPanel.add(logoLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 70, 90));

        submitBtn.setBackground(new java.awt.Color(0, 0, 0));
        submitBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(244, 189, 108));
        submitBtn.setText("Submit");
        submitBtn.setBorder(null);
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        mainPanel.add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 110, 30));

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Go Back");
        backBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), java.awt.Color.darkGray));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        mainPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uIDFieldActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        try{
            Checker check = new Checker();
            if(uIDField.getText().isEmpty() || emailField.getText().isEmpty() || cnicField.getText().isEmpty()){
                JOptionPane.showMessageDialog((Component)null, "Please enter credentials!");
            }  
            else if(!check.validateFPwd(uIDField.getText(), emailField.getText(), cnicField.getText())){
                JOptionPane.showMessageDialog((Component)null, "Account not found!");
            }
            else{
                JOptionPane.showMessageDialog((Component)null, "Account found!");
                dispose();
                ForgotPassword2 fpass = new ForgotPassword2(uIDField.getText());
                fpass.setVisible(true);                //frame will only be visible with set "true"
                fpass.setLocationRelativeTo(null);     //for opening in center
            }
        }catch(Exception ex){
            System.out.println(ex.toString());
        }
        
   
    }//GEN-LAST:event_submitBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        dispose();
        Login login = new Login();
        login.setVisible(true);                //frame will only be visible with set "true"
        login.setLocationRelativeTo(null);     //for opening in center
    }//GEN-LAST:event_backBtnActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void cnicFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnicFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField cnicField;
    private javax.swing.JLabel cnicLb;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLb;
    private javax.swing.JLabel headerLb;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel logoLb;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField uIDField;
    private javax.swing.JLabel uIDLb;
    // End of variables declaration//GEN-END:variables
}
