
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fujitsu
 */
public class Voting extends javax.swing.JFrame {
private String uid;
    /**
     * Creates new form Voting
     */
    public Voting(String uid) {
                this.uid=uid;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        logoLb = new javax.swing.JLabel();
        HomeLb = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        AboutusLb = new javax.swing.JLabel();
        FeedbackLb = new javax.swing.JLabel();
        logoLb1 = new javax.swing.JLabel();
        footerPanel = new javax.swing.JPanel();
        voting_label = new javax.swing.JLabel();
        vote_iconLabel = new javax.swing.JLabel();
        regAsVoter_btn = new javax.swing.JButton();
        regelection_btn = new javax.swing.JButton();
        activeElect_btn = new javax.swing.JButton();
        myRegElec_btn = new javax.swing.JButton();
        casteVote_btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(231, 231, 231));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Go Back");
        backBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), java.awt.Color.black));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        mainPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 70, 30));

        headerPanel.setBackground(new java.awt.Color(0, 0, 0));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        headerPanel.add(logoLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 130, 80));

        HomeLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HomeLb.setForeground(new java.awt.Color(255, 255, 255));
        HomeLb.setText("Home");
        HomeLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        HomeLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeLbMouseClicked(evt);
            }
        });
        headerPanel.add(HomeLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 60, -1));

        logoutBtn.setBackground(new java.awt.Color(244, 189, 108));
        logoutBtn.setText("Log out");
        logoutBtn.setBorder(null);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        headerPanel.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 80, 30));

        AboutusLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AboutusLb.setForeground(new java.awt.Color(255, 255, 255));
        AboutusLb.setText("About us");
        AboutusLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AboutusLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AboutusLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutusLbMouseClicked(evt);
            }
        });
        headerPanel.add(AboutusLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 60, -1));

        FeedbackLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FeedbackLb.setForeground(new java.awt.Color(255, 255, 255));
        FeedbackLb.setText("Feedback");
        FeedbackLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FeedbackLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        FeedbackLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FeedbackLbMouseClicked(evt);
            }
        });
        headerPanel.add(FeedbackLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 60, -1));

        logoLb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo_cropped.png"))); // NOI18N
        headerPanel.add(logoLb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 130, 80));

        mainPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 90));

        footerPanel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        mainPanel.add(footerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, -1, -1));

        voting_label.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        voting_label.setText("Voting");
        mainPanel.add(voting_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        vote_iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting.png"))); // NOI18N
        mainPanel.add(vote_iconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 140, 70));

        regAsVoter_btn.setBackground(new java.awt.Color(244, 189, 108));
        regAsVoter_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regAsVoter_btn.setText("Register as voter");
        regAsVoter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regAsVoter_btnActionPerformed(evt);
            }
        });
        mainPanel.add(regAsVoter_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 200, -1));

        regelection_btn.setBackground(new java.awt.Color(244, 189, 108));
        regelection_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regelection_btn.setText("Register Election");
        regelection_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regelection_btnActionPerformed(evt);
            }
        });
        mainPanel.add(regelection_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 200, -1));

        activeElect_btn.setBackground(new java.awt.Color(244, 189, 108));
        activeElect_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        activeElect_btn.setText("View Active elections");
        activeElect_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeElect_btnActionPerformed(evt);
            }
        });
        mainPanel.add(activeElect_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 200, -1));

        myRegElec_btn.setBackground(new java.awt.Color(244, 189, 108));
        myRegElec_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        myRegElec_btn.setText("My Registered Elections");
        myRegElec_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myRegElec_btnActionPerformed(evt);
            }
        });
        mainPanel.add(myRegElec_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 200, -1));

        casteVote_btn1.setBackground(new java.awt.Color(244, 189, 108));
        casteVote_btn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        casteVote_btn1.setText("Cast Vote");
        casteVote_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casteVote_btn1ActionPerformed(evt);
            }
        });
        mainPanel.add(casteVote_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        dispose();
        MainScreen main = new MainScreen(uid);
        main.setVisible(true);                //frame will only be visible with set "true"
        main.setLocationRelativeTo(null);     //for opening in center
    }//GEN-LAST:event_backBtnActionPerformed

    private void HomeLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeLbMouseClicked
        dispose();
        MainScreen main = new MainScreen(uid);
        main.setVisible(true);                //frame will only be visible with set "true"
        main.setLocationRelativeTo(null);     //for opening in center
    }//GEN-LAST:event_HomeLbMouseClicked

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        int result = JOptionPane.showConfirmDialog(null,"Are you sure you want to log out?", "Logout Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(result == JOptionPane.YES_OPTION){
            dispose();
            Homepage home = new Homepage();
            home.setVisible(true);                //frame will only be visible with set "true"
            home.setLocationRelativeTo(null);     //for opening in center
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void AboutusLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutusLbMouseClicked
        // TODO add your handling code here:
        
        AboutUs about= new AboutUs();
        about.setVisible(true);
        about.setLocationRelativeTo (null);
    }//GEN-LAST:event_AboutusLbMouseClicked

    private void FeedbackLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FeedbackLbMouseClicked
        // TODO add your handling code here:
        
        Feedback feed = new Feedback(uid);
        feed.setVisible(true);                //frame will only be visible with set "true"
        feed.setLocationRelativeTo(null);     //for opening in center
    }//GEN-LAST:event_FeedbackLbMouseClicked

    private void activeElect_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeElect_btnActionPerformed
        // TODO add your handling code here:
         dispose();
        active_elections elec = new active_elections();
        elec.setVisible(true);                //frame will only be visible with set "true"
        elec.setLocationRelativeTo(null); 
    }//GEN-LAST:event_activeElect_btnActionPerformed

    private void regelection_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regelection_btnActionPerformed
        // TODO add your handling code here:
        dispose();
        this.uid=uid;
        register_Vote reg = new register_Vote(uid);
        reg.setVisible(true);                //frame will only be visible with set "true"
        reg.setLocationRelativeTo(null);  
    }//GEN-LAST:event_regelection_btnActionPerformed

    private void regAsVoter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regAsVoter_btnActionPerformed
        // TODO add your handling code here:
         dispose();
       registrationVote cvote = new registrationVote(uid);
        cvote.setVisible(true);                //frame will only be visible with set "true"
        cvote.setLocationRelativeTo(null); 
    }//GEN-LAST:event_regAsVoter_btnActionPerformed

    private void myRegElec_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myRegElec_btnActionPerformed
        // TODO add your handling code here:
          dispose();
        MyReg_elections Myreg = new MyReg_elections(uid);
        Myreg.setVisible(true);                //frame will only be visible with set "true"
        Myreg.setLocationRelativeTo(null); 
    }//GEN-LAST:event_myRegElec_btnActionPerformed

    private void casteVote_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casteVote_btn1ActionPerformed
        // TODO add your handling code here:
        dispose();
        casteVote vote = new casteVote(uid);
        vote.setVisible(true);
    }//GEN-LAST:event_casteVote_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Voting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Voting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Voting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Voting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Voting(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutusLb;
    private javax.swing.JLabel FeedbackLb;
    private javax.swing.JLabel HomeLb;
    private javax.swing.JButton activeElect_btn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton casteVote_btn1;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel logoLb;
    private javax.swing.JLabel logoLb1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton myRegElec_btn;
    private javax.swing.JButton regAsVoter_btn;
    private javax.swing.JButton regelection_btn;
    private javax.swing.JLabel vote_iconLabel;
    private javax.swing.JLabel voting_label;
    // End of variables declaration//GEN-END:variables
}
