
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hunia
 */
public class ElectionCreateEdit4 extends javax.swing.JFrame {
    private String categoryType;
    private String uid;
    private static ArrayList<ArrayList<String>> data;
    /**
     * Creates new form ElectionScreen5
     */
    public ElectionCreateEdit4(String categoryType, String uid, ArrayList<ArrayList<String>> data) {
        this.categoryType = categoryType;
        this.uid = uid;
        this.data = data;
        System.out.println(data);
        initComponents();
        displayData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        applicantTypeGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        logoLb = new javax.swing.JLabel();
        HomeLb = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        AboutusLb = new javax.swing.JLabel();
        FeedbackLb = new javax.swing.JLabel();
        ProfileLb = new javax.swing.JLabel();
        footerPanel = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        infoPanel = new javax.swing.JPanel();
        groupBtn = new javax.swing.JRadioButton();
        candidateBtn = new javax.swing.JRadioButton();
        nameLb = new javax.swing.JLabel();
        headerLb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(231, 231, 231));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(0, 0, 0));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_full_w.png"))); // NOI18N
        headerPanel.add(logoLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 130, 80));

        HomeLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HomeLb.setForeground(new java.awt.Color(255, 255, 255));
        HomeLb.setText("Home");
        HomeLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        headerPanel.add(HomeLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 60, -1));

        logoutBtn.setBackground(new java.awt.Color(244, 189, 108));
        logoutBtn.setText("Log out");
        logoutBtn.setBorder(null);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        headerPanel.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 80, 30));

        AboutusLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AboutusLb.setForeground(new java.awt.Color(255, 255, 255));
        AboutusLb.setText("About us");
        AboutusLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AboutusLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AboutusLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutusLbMouseClicked(evt);
            }
        });
        headerPanel.add(AboutusLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 60, -1));

        FeedbackLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FeedbackLb.setForeground(new java.awt.Color(255, 255, 255));
        FeedbackLb.setText("Feedback");
        FeedbackLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FeedbackLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        FeedbackLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FeedbackLbMouseClicked(evt);
            }
        });
        headerPanel.add(FeedbackLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 60, -1));

        ProfileLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ProfileLb.setForeground(new java.awt.Color(255, 255, 255));
        ProfileLb.setText("Profile");
        ProfileLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProfileLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ProfileLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileLbMouseClicked(evt);
            }
        });
        headerPanel.add(ProfileLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 60, -1));

        mainPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 90));

        footerPanel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        mainPanel.add(footerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, 10));

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Go Back");
        backBtn.setBorder(null);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        mainPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 70, 30));

        nextBtn.setBackground(new java.awt.Color(0, 0, 0));
        nextBtn.setForeground(new java.awt.Color(255, 255, 255));
        nextBtn.setText("Next");
        nextBtn.setBorder(null);
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        mainPanel.add(nextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 450, 70, 30));

        infoPanel.setBackground(new java.awt.Color(244, 189, 108));
        infoPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray));
        infoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        applicantTypeGroup.add(groupBtn);
        groupBtn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        groupBtn.setText("Group/Party");
        groupBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                groupBtnMouseClicked(evt);
            }
        });
        infoPanel.add(groupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 110, -1));

        applicantTypeGroup.add(candidateBtn);
        candidateBtn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        candidateBtn.setText("Candidate");
        candidateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                candidateBtnMouseClicked(evt);
            }
        });
        infoPanel.add(candidateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 110, -1));

        nameLb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nameLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLb.setText("Please Select");
        infoPanel.add(nameLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 470, 30));

        mainPanel.add(infoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 470, 190));

        headerLb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        headerLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLb.setText("Election - Applicant Type");
        mainPanel.add(headerLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 470, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void displayData(){
        try{  
            if(categoryType.equalsIgnoreCase("candidate")){
                candidateBtn.setSelected(true);
            } 
            else if(categoryType.equalsIgnoreCase("group")){
                groupBtn.setSelected(true);
            }
            
        }catch(Exception ex){
            System.out.println(ex.toString());
        }
        
    }
    
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        if(categoryType.equalsIgnoreCase("organization")){
            dispose();
            ElectionCreateEdit3_1 orgInfo = new ElectionCreateEdit3_1(uid, data);
            orgInfo.setVisible(true);                //frame will only be visible with set "true"
            orgInfo.setLocationRelativeTo(null);     //for opening in center
        }
        else if(categoryType.equalsIgnoreCase("government")){
            dispose();
            ElectionCreateEdit3_2 governInfo = new ElectionCreateEdit3_2(uid, data);
            governInfo.setVisible(true);                //frame will only be visible with set "true"
            governInfo.setLocationRelativeTo(null);     //for opening in center
        
        }
        else if(categoryType.equalsIgnoreCase("referendum")){
            dispose();
            ElectionCreateEdit3_3 referInfo = new ElectionCreateEdit3_3(uid, data);
            referInfo.setVisible(true);                //frame will only be visible with set "true"
            referInfo.setLocationRelativeTo(null);     //for opening in center
        
        }
        else{
            dispose();
            ElectionCreateEdit3 customInfo = new ElectionCreateEdit3(uid, data);
            customInfo.setVisible(true);                //frame will only be visible with set "true"
            customInfo.setLocationRelativeTo(null);     //for opening in center
        
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        if(groupBtn.isSelected()){
            if(data.get(data.size()-1).get(0).equalsIgnoreCase("candidate")){
                int result = JOptionPane.showConfirmDialog(null,"Are you sure you want to change applicant type? (Previosuly added candidate data will reset)", "Applicant Type Reset", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if(result == JOptionPane.YES_OPTION){
                    while(data.get(data.size()-1).get(0).equalsIgnoreCase("candidate")){
                        data.remove(data.size()-1);
                    }
                }   
            }
            
            dispose();
            ElectionCreateEdit4_2 groupInfo = new ElectionCreateEdit4_2(categoryType, uid, data);
            groupInfo.setVisible(true);                //frame will only be visible with set "true"
            groupInfo.setLocationRelativeTo(null);     //for opening in center
        }
        else if(candidateBtn.isSelected()){
            if(data.get(data.size()-1).get(0).equalsIgnoreCase("group")){
                int result = JOptionPane.showConfirmDialog(null,"Are you sure you want to change applicant type? (Previosuly added group data will reset)", "Applicant Type Reset", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if(result == JOptionPane.YES_OPTION){
                    while(data.get(data.size()-1).get(0).equalsIgnoreCase("group")){
                        data.remove(data.size()-1);
                    }
                }   
            }
            dispose();
            ElectionCreateEdit4_1 candidateInfo = new ElectionCreateEdit4_1(categoryType, uid, data);
            candidateInfo.setVisible(true);                //frame will only be visible with set "true"
            candidateInfo.setLocationRelativeTo(null);     //for opening in center
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select an applicant type!");
        }  
    }//GEN-LAST:event_nextBtnActionPerformed

    private void AboutusLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutusLbMouseClicked
        // TODO add your handling code here:
        dispose();
        AboutUs about= new AboutUs();
        about.setVisible(true);
        about.setLocationRelativeTo (null);
    }//GEN-LAST:event_AboutusLbMouseClicked

    private void FeedbackLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FeedbackLbMouseClicked
        // TODO add your handling code here:
        
        Feedback feed = new Feedback(uid);
        feed.setVisible(true);                //frame will only be visible with set "true"
        feed.setLocationRelativeTo(null);     //for opening in center
    }//GEN-LAST:event_FeedbackLbMouseClicked

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        int result = JOptionPane.showConfirmDialog(null,"Are you sure you want to log out?", "Logout Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(result == JOptionPane.YES_OPTION){
            dispose();
            Homepage home = new Homepage();
            home.setVisible(true);                //frame will only be visible with set "true"
            home.setLocationRelativeTo(null);     //for opening in center
        } 
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void ProfileLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileLbMouseClicked
        Profile1 profile = new Profile1(uid);
        profile.setVisible(true);                //frame will only be visible with set "true"
        profile.setLocationRelativeTo(null);     //for opening in center
    }//GEN-LAST:event_ProfileLbMouseClicked

    private void candidateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_candidateBtnMouseClicked
        categoryType="candidate";
    }//GEN-LAST:event_candidateBtnMouseClicked

    private void groupBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupBtnMouseClicked
        categoryType="group";
    }//GEN-LAST:event_groupBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElectionCreateEdit4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElectionCreateEdit4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElectionCreateEdit4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElectionCreateEdit4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElectionCreateEdit4("", null, new ArrayList<>()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutusLb;
    private javax.swing.JLabel FeedbackLb;
    private javax.swing.JLabel HomeLb;
    private javax.swing.JLabel ProfileLb;
    private javax.swing.ButtonGroup applicantTypeGroup;
    private javax.swing.JButton backBtn;
    private javax.swing.JRadioButton candidateBtn;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JRadioButton groupBtn;
    private javax.swing.JLabel headerLb;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel logoLb;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameLb;
    private javax.swing.JButton nextBtn;
    // End of variables declaration//GEN-END:variables
}
