
import java.awt.Component;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fujitsu
 */
public class Feedback extends javax.swing.JFrame {
    private String uid;


    /**
     * Creates new form Feedback
     */
    public Feedback(String uid) {
                this.uid = uid;


        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        sendus_fdbk_label = new javax.swing.JLabel();
        experience_label = new javax.swing.JLabel();
        fdbk_tf = new javax.swing.JTextField();
        rateus_label = new javax.swing.JLabel();
        rating_cb = new javax.swing.JComboBox<>();
        send_fdbk_btn = new javax.swing.JButton();
        fdbk_label = new javax.swing.JLabel();
        logo_label = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 189, 108));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        sendus_fdbk_label.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        sendus_fdbk_label.setForeground(new java.awt.Color(255, 255, 255));
        sendus_fdbk_label.setText("SEND US YOUR FEEDBACK!");

        experience_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        experience_label.setForeground(new java.awt.Color(255, 255, 255));
        experience_label.setText("Describe your experience here");

        fdbk_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdbk_tfActionPerformed(evt);
            }
        });

        rateus_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rateus_label.setForeground(new java.awt.Color(255, 255, 255));
        rateus_label.setText("Rate Us");

        rating_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", " " }));

        send_fdbk_btn.setBackground(new java.awt.Color(244, 189, 108));
        send_fdbk_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        send_fdbk_btn.setText("SEND FEEDBACK");
        send_fdbk_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_fdbk_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(rateus_label))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(rating_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(send_fdbk_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(experience_label, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendus_fdbk_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fdbk_tf, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(147, 147, 147))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sendus_fdbk_label)
                .addGap(18, 18, 18)
                .addComponent(experience_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fdbk_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rateus_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rating_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(send_fdbk_btn)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 530, 250));

        fdbk_label.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        fdbk_label.setText("Feedback");
        jPanel1.add(fdbk_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo_cropped_black.png"))); // NOI18N
        jPanel1.add(logo_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 70, 60));

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Go Back");
        backBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), java.awt.Color.darkGray));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 30));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 730, 10));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fdbk_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdbk_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fdbk_tfActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void send_fdbk_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_fdbk_btnActionPerformed
            try{
        Checker check = new Checker();
            String feedback_desc = null;
            int rating= 0;

             rating = Integer.parseInt(rating_cb.getSelectedItem().toString());
            feedback_desc=fdbk_tf.getText();
        int result = JOptionPane.showConfirmDialog(null,"Are you sure to submit your feedback ?", "Feedback Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if(result == JOptionPane.YES_OPTION){
                    IDGenerator idgen = new IDGenerator();
                 this.uid=uid;
                    Statement stmt = check.connectSQL();
                    String query = "INSERT INTO Feedbacks (FEEDBACK_ID,FEEDBACK_DESCRIPTION,RATING, USER_ID) VALUES ('"+idgen.generateFeedbackID()+"', '"+feedback_desc+"', "+rating+",'"+uid+"')";
                    stmt.executeUpdate(query);
                  JOptionPane.showMessageDialog((Component)null, "Feedback Successfully Submitted!");
                  dispose();
                    MainScreen main = new MainScreen(uid);
                    main.setVisible(true);                //frame will only be visible with set "true"
                    main.setLocationRelativeTo(null);

                    
                } 
            }
            catch(Exception e){
                System.out.println(e.toString());
            }
    }//GEN-LAST:event_send_fdbk_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Feedback(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel experience_label;
    private javax.swing.JLabel fdbk_label;
    private javax.swing.JTextField fdbk_tf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel logo_label;
    private javax.swing.JLabel rateus_label;
    private javax.swing.JComboBox<String> rating_cb;
    private javax.swing.JButton send_fdbk_btn;
    private javax.swing.JLabel sendus_fdbk_label;
    // End of variables declaration//GEN-END:variables
}
