
import java.sql.Statement;
import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hunia
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        logoLb = new javax.swing.JLabel();
        AboutusLb = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        signupBtn = new javax.swing.JButton();
        dividerPanel = new javax.swing.JPanel();
        bodyPanel = new javax.swing.JPanel();
        welcomeLb = new javax.swing.JLabel();
        getStartedBtn = new javax.swing.JButton();
        footerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(231, 231, 231));
        mainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainPanel.setInheritsPopupMenu(true);
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(0, 0, 0));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_full_w.png"))); // NOI18N
        headerPanel.add(logoLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 130, 80));

        AboutusLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AboutusLb.setForeground(new java.awt.Color(255, 255, 255));
        AboutusLb.setText("About us");
        AboutusLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AboutusLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AboutusLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutusLbMouseClicked(evt);
            }
        });
        headerPanel.add(AboutusLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 60, -1));

        loginBtn.setBackground(new java.awt.Color(244, 189, 108));
        loginBtn.setText("Login");
        loginBtn.setBorder(null);
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.setName(""); // NOI18N
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        headerPanel.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 80, 30));

        signupBtn.setBackground(new java.awt.Color(244, 189, 108));
        signupBtn.setText("Sign up");
        signupBtn.setBorder(null);
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });
        headerPanel.add(signupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 80, 30));

        dividerPanel.setRequestFocusEnabled(false);
        dividerPanel.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout dividerPanelLayout = new javax.swing.GroupLayout(dividerPanel);
        dividerPanel.setLayout(dividerPanelLayout);
        dividerPanelLayout.setHorizontalGroup(
            dividerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        dividerPanelLayout.setVerticalGroup(
            dividerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        headerPanel.add(dividerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, -1, -1));

        mainPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 90));

        bodyPanel.setBackground(new java.awt.Color(244, 189, 108));
        bodyPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray));
        bodyPanel.setForeground(new java.awt.Color(255, 186, 98));
        bodyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeLb.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        welcomeLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLb.setText("Welcome to Online Voting System!");
        bodyPanel.add(welcomeLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 690, 40));

        getStartedBtn.setBackground(new java.awt.Color(0, 0, 0));
        getStartedBtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        getStartedBtn.setForeground(new java.awt.Color(255, 255, 255));
        getStartedBtn.setText("Get Started");
        getStartedBtn.setBorderPainted(false);
        getStartedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getStartedBtnActionPerformed(evt);
            }
        });
        bodyPanel.add(getStartedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 187, 48));

        mainPanel.add(bodyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 690, 260));

        footerPanel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        mainPanel.add(footerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        dispose();
        Login login = new Login();
        login.setVisible(true);                //frame will only be visible with set "true"
        login.setLocationRelativeTo(null);     //for opening in center
    }//GEN-LAST:event_loginBtnActionPerformed

    private void getStartedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getStartedBtnActionPerformed
        dispose();
        Login login = new Login();
        login.setVisible(true);                //frame will only be visible with set "true"
        login.setLocationRelativeTo(null);     //for opening in center
    }//GEN-LAST:event_getStartedBtnActionPerformed

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
        dispose();
        Signup signup = new Signup();
        signup.setVisible(true);                //frame will only be visible with set "true"
        signup.setLocationRelativeTo(null);     //for opening in center
    }//GEN-LAST:event_signupBtnActionPerformed

    private void AboutusLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutusLbMouseClicked
        AboutUs about= new AboutUs();
        about.setVisible(true);
        about.setLocationRelativeTo (null);
    }//GEN-LAST:event_AboutusLbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Homepage home = new Homepage();
                home.setVisible(true);                //frame will only be visible with set "true"
                home.setLocationRelativeTo(null);  
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutusLb;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel dividerPanel;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JButton getStartedBtn;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel logoLb;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton signupBtn;
    private javax.swing.JLabel welcomeLb;
    // End of variables declaration//GEN-END:variables
}
