
import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.awt.Component;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hunia
 */
public class Profile1 extends javax.swing.JFrame {
    private String uid;
    /**
     * Creates new form Profile
     */
    public Profile1(String uid) {
        this.uid = uid;
        
        initComponents();
        displayData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        logoLb = new javax.swing.JLabel();
        headerLb = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        emailLb = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        fnameLabel = new javax.swing.JLabel();
        fnameField = new javax.swing.JTextField();
        lnameLabel = new javax.swing.JLabel();
        lnameField = new javax.swing.JTextField();
        ageLb = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        PhoneLb = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        cnicLb = new javax.swing.JLabel();
        cnicField = new javax.swing.JFormattedTextField();
        uIDLb = new javax.swing.JLabel();
        uIDField = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        continueBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(244, 189, 108));
        mainPanel.setPreferredSize(new java.awt.Dimension(690, 530));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo_cropped_black.png"))); // NOI18N
        mainPanel.add(logoLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 70, 90));

        headerLb.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        headerLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLb.setText("Profile");
        mainPanel.add(headerLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 650, 50));

        loginPanel.setBackground(new java.awt.Color(0, 0, 0));
        loginPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailLb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        emailLb.setForeground(new java.awt.Color(244, 189, 108));
        emailLb.setText("Email");
        loginPanel.add(emailLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 90, 30));

        emailField.setEditable(false);
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        loginPanel.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 480, 30));

        fnameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fnameLabel.setForeground(new java.awt.Color(244, 189, 108));
        fnameLabel.setText("First Name");
        loginPanel.add(fnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, 30));

        fnameField.setEditable(false);
        fnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameFieldActionPerformed(evt);
            }
        });
        loginPanel.add(fnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 170, 30));

        lnameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lnameLabel.setForeground(new java.awt.Color(244, 189, 108));
        lnameLabel.setText("Last Name");
        loginPanel.add(lnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 100, 30));

        lnameField.setEditable(false);
        lnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameFieldActionPerformed(evt);
            }
        });
        loginPanel.add(lnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 170, 30));

        ageLb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ageLb.setForeground(new java.awt.Color(244, 189, 108));
        ageLb.setText("Age");
        loginPanel.add(ageLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 90, 30));

        ageField.setEditable(false);
        ageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageFieldActionPerformed(evt);
            }
        });
        loginPanel.add(ageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 100, 30));

        PhoneLb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PhoneLb.setForeground(new java.awt.Color(244, 189, 108));
        PhoneLb.setText("Phone No.");
        loginPanel.add(PhoneLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 110, 30));

        phoneField.setEditable(false);
        phoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFieldActionPerformed(evt);
            }
        });
        loginPanel.add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 200, 30));

        cnicLb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cnicLb.setForeground(new java.awt.Color(244, 189, 108));
        cnicLb.setText("CNIC");
        loginPanel.add(cnicLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 30));

        cnicField.setEditable(false);
        cnicField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnicFieldActionPerformed(evt);
            }
        });
        loginPanel.add(cnicField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 200, 30));

        uIDLb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        uIDLb.setForeground(new java.awt.Color(244, 189, 108));
        uIDLb.setText("User ID");
        loginPanel.add(uIDLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 90, 30));

        uIDField.setEditable(false);
        uIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uIDFieldActionPerformed(evt);
            }
        });
        loginPanel.add(uIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 100, 30));

        mainPanel.add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 650, 250));

        updateBtn.setBackground(new java.awt.Color(0, 0, 0));
        updateBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(244, 189, 108));
        updateBtn.setText("Update");
        updateBtn.setBorder(null);
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        mainPanel.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 110, 30));

        continueBtn.setBackground(new java.awt.Color(0, 0, 0));
        continueBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        continueBtn.setForeground(new java.awt.Color(244, 189, 108));
        continueBtn.setText("Continue");
        continueBtn.setBorder(null);
        continueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtnActionPerformed(evt);
            }
        });
        mainPanel.add(continueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayData(){
        try{
            Checker check = new Checker();
            DB mydb = check.connectMongo();
            DBCollection collection = mydb.getCollection("Person");
            uid = "u-1";
            BasicDBObject key = new BasicDBObject();
            key.put("user_ID", uid);
            DBCursor result = collection.find(key);
            
            result.hasNext();
            DBObject obj = result.next();

            fnameField.setText((String)obj.get("firstName"));
            lnameField.setText((String)obj.get("lastName"));
            emailField.setText((String)obj.get("email"));
            cnicField.setText((String)obj.get("cnic"));
            ageField.setText((String)obj.get("age"));
            phoneField.setText((String)obj.get("phoneNo"));
            uIDField.setText(this.uid);
             
            }catch(Exception ex){
            System.out.println(ex.toString());
        }
    }
    
    
    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void fnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameFieldActionPerformed

    private void ageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageFieldActionPerformed

    private void phoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFieldActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        try{
            Checker check = new Checker();
            String pwd = JOptionPane.showInputDialog((Component)null,"Please enter your password:");
            Statement stmt = check.connectSQL();
            
            DB mydb = check.connectMongo();
            DBCollection collection = mydb.getCollection("Person");
            
            BasicDBObject key = new BasicDBObject();
            key.put("user_ID", uid);
            key.put("password", pwd);
            DBCursor result = collection.find(key);
            
            //if password is entered correctly then move forward
            if(result.hasNext()){
                dispose();
                Profile2 profile = new Profile2(uid);
                profile.setVisible(true);                //frame will only be visible with set "true"
                profile.setLocationRelativeTo(null);     //for opening in center
            }
            else if(!result.hasNext() && pwd!=null){
                JOptionPane.showMessageDialog((Component)null, "Invalid Password!");
            }
        }catch(Exception ex){
            System.out.println(ex.toString());
        }
        
        

    }//GEN-LAST:event_updateBtnActionPerformed

    private void continueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtnActionPerformed
        dispose();
    }//GEN-LAST:event_continueBtnActionPerformed

    private void lnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameFieldActionPerformed

    private void cnicFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnicFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicFieldActionPerformed

    private void uIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uIDFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile1(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PhoneLb;
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageLb;
    private javax.swing.JFormattedTextField cnicField;
    private javax.swing.JLabel cnicLb;
    private javax.swing.JButton continueBtn;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLb;
    private javax.swing.JTextField fnameField;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JLabel headerLb;
    private javax.swing.JTextField lnameField;
    private javax.swing.JLabel lnameLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logoLb;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTextField uIDField;
    private javax.swing.JLabel uIDLb;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
